const ErrorConstants = {
  SUCCESS: "SUCCESS",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_ALLOWED: "NOT_ALLOWED",
};

export default ErrorConstants;
